from activities.abstract_activity import AbstractActivity
from activities.contact_activity import ContactActivity
from activities.main_menu_activity import MainMenuActivity
from activities.auth_activity import AuthActivity
# from activities.activity_container import ActivityContainer
